services:
  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"

  rq-worker:
    build: .
    depends_on:
      - redis-server
    environment:
      - REDIS_URL=redis://redis-server:6379/0
    volumes:
      - "./home/static/AI_Scripts:/AI_Scripts"
      - "./home/static/AI_Scripts/Identified_Person:/Identified_Person"
    working_dir: /AI_Scripts
    command: rq worker --with-scheduler
    deploy:
      resources:
        limits:
          cpus: "0.5"  # Limit CPU usage if needed
          memory: "512M"  # Limit memory usage if needed
